# As per https://github.com/pypa/setuptools/blob/main/docs/userguide/quickstart.rst
[build-system]
requires = ["setuptools >= 40.6.0", "wheel", "numpy >= 1.20"]
build-backend = "setuptools.build_meta"
