# -*- coding: utf-8 -*-
#
# Copyright 2023 Nicolás Cardiel
#
# This file is part of simelastic
#
# SPDX-License-Identifier: GPL-3.0+
# License-Filename: LICENSE
#

DEFAULT_BALL_RADIUS = 0.5

DEFAULT_CUBOID3D_XMIN = -5
DEFAULT_CUBOID3D_XMAX = 5
DEFAULT_CUBOID3D_YMIN = -5
DEFAULT_CUBOID3D_YMAX = 5
DEFAULT_CUBOID3D_ZMIN = -5
DEFAULT_CUBOID3D_ZMAX = 5

DEFAULT_CYLINDER_RADIUS = 5
DEFAULT_CYLINDER_HEIGHT = 10
